### ISSUE TITLE
Question: Is it possible to override styles for SelectLabel?

### ISSUE THREAD

**Issue by vharmain** [iulian-radu-at/react-select-material-ui#10]
First of all thanks for `react-select-material-ui`! 💯

Is it somehow possible to provide custom styles for the `SelectLabel`? I would like to conditionally display "error" colour.

I mean something like this: 
![image](https://user-images.githubusercontent.com/19185700/58075940-97570080-7bb1-11e9-8113-77e8dcb88a11.png)

Thanks!

**Comment by iulian-radu-at** [comment]
Hi. Not this week. But good input so most likely you will have it next week :)

**Comment by iulian-radu-at** [comment]
Hi @vharmain,
I added the possibility to style the label in v3.0.0 by using InputLabelProps.className or InputLabelProps.style.
Please check it and let me know if does what you wanted.
More info find you in Readme.

**Comment by vharmain** [comment]
Thank you so much for the new version!

However, when I now try to build my bundle with Webpack I'm getting this:
```bash
ERROR in ./node_modules/react-select-material-ui/lib/SelectDropdown.js
Module not found: Error: Can't resolve 'react-select/lib/Creatable' in '/Users/vaotjuha/lipas/lipas/webapp/node_modules/react-select-material-ui/lib'
 @ ./node_modules/react-select-material-ui/lib/SelectDropdown.js 28:18-55
 @ ./node_modules/react-select-material-ui/lib/ReactSelectMaterialUi.js
 @ ./node_modules/react-select-material-ui/lib/index.js
 @ ./src/js/index.js
``` 
Am I missing something?
