### ISSUE TITLE
Colors from theme not used

### ISSUE THREAD

**Issue by adberard** [iulian-radu-at/react-select-material-ui#13]
Hello, Im having a bit of trouble with the styles of react-select-material-ui

![react-select-material-ui-bug-theme](https://user-images.githubusercontent.com/23508913/62693958-bd7f8600-b9d3-11e9-97b8-3aa5d06fe487.png)

The component does not use the theme.palette from the style context provided by material-ui.
So in a dark theme the options dropdown items end up white on a white background. This background should be the same color of theme.palette.background.paper instead of purely white.

Im trying to find how to customise the options elements but I fail to find how to access  [styles](https://react-select.com/styles) prop from react-select.

**Comment by jsmith-phoenix** [comment]
++ on this issue

**Comment by iulian-radu-at** [comment]
Hi,

I added in v4.3.0 an example in storybook how to style the component. Also I made changes in the code to support the styling via SelectProps.styles prop.

Please check if it is what you wanted and let me know.

**Comment by iulian-radu-at** [comment]
Closed as there is no answer from issue reporter.

**Comment by jsmith-phoenix** [comment]
FYI: After the lastest update this has been resolved (for me). Thanks!

**Comment by devans-k4** [comment]
I have added all the appropriate styles via SelectProps but still seem to figure out how to update the bottom border of the input when it is active. Seems to have a defaulted blue color that Material UI uses
