### ISSUE TITLE
Select options above text field

### ISSUE THREAD

**Issue by samosaara** [iulian-radu-at/react-select-material-ui#14]
Does this library support "auto hoisting" the selection options above the text field when there is no space underneath it? I tried using it inside a material UI bottom drawer it just added a scrollbar so it could fit the selection panel

I was expecting: 
![image](https://user-images.githubusercontent.com/1809521/62825616-4984df80-bb85-11e9-9b16-5ca559c7f7fd.png)

What I got:
![image](https://media.giphy.com/media/ZXAWjyoxOnEMDxRend/giphy.gif)

Am I missing something or there is no such option? I know I'll most likely face issues with the selection panel underneath the shadow overlay or something but this is far from it

**Comment by iulian-radu-at** [comment]
Hi,

This component is only a "wrapper" for react-select, so your request is more appropriate for react-select component than here.

Sorry, but I cannot help you with this.
