### ISSUE TITLE
Multi-select select multiple at once

### ISSUE THREAD

**Issue by jsmith-phoenix** [iulian-radu-at/react-select-material-ui#15]
Is it possible for the select menu to stay open until the user clicks-away? Users would like to be able to open the menu and browse through the options, selecting them all, and then hitting enter to commit the selection. Apologies, if i've missed support of this already.

**Comment by iulian-radu-at** [comment]
You need to ask the react-select component explicitly for this.

```
 <ReactSelectMaterialUi
        SelectProps={{
          isMulti: true,
          closeMenuOnSelect: false
        }}
      />
```

Now there is a storybook for this use case.
