### ISSUE TITLE
Broken SourceMaps

### ISSUE THREAD

**Issue by RoiEXLab** [iulian-radu-at/react-select-material-ui#19]
Hi, I just noticed that your source-maps that are shipped with the dependency are essentially broken.
I'm not an expert by any means, but the way I understand source maps is that they provide a mapping from a transpiled version of the code to the original source, which isn't present in the published npm version.
Therefore my webpack pre-compilation-step generates a lot of warnings because the existing js.map files reference non-existent ts/tsx files.

It would be nice if this could be fixed as well :-)

**Comment by iulian-radu-at** [comment]
Fixed in v5.0.2

**Comment by RoiEXLab** [comment]
Thanks 👍
