### ISSUE TITLE
Support for placeholder text

### ISSUE THREAD

**Issue by korshavn** [iulian-radu-at/react-select-material-ui#2]
Hi.
Would love if the select component could display a grey placeholder text..

![image](https://user-images.githubusercontent.com/462345/51791567-705d6480-21a5-11e9-8cf4-771344230da9.png)

In the picture above, the first input is a traditional Select (react-select). The second is with your library, and would prefer it. The others are just a free text and two date inputs.

I can see you have written "ignoring placeholder in SelectProps" in the doc. Is there a reason why?

Using together with redux-form <Field>:

`
               const renderReactSelectMaterialUIInput = (field) => {
                 console.log("renderReactSelectMaterialUIInput", field);
                 return <SingleSelect
                   style={{width: "85%"}}
                   SelectProps={{
                     placeholder: <FormattedMessage id="page.search.conductor"/>
                   }}
                   placeholder={<FormattedMessage id="page.search.conductor"/>}
                   value={field.input.value}
                   options={field.options}
                   onChange={field.input.onChange}
                 />
               };

               ...

               <Field
                  style={{width: "85%"}}
                  name="conductor"
                  component={renderReactSelectMaterialUIInput}
                  value={this.state.selectedConductor}
                  options={this.props.conductors}
                  onChange={this.handleConductorChange}
                /><br/><br/>

`

Best regards,
Leif John K.

**Comment by korshavn** [comment]
I will be using your other project "selectrix" instead. Great work! :-)

**Comment by iulian-radu-at** [comment]
Feature request took into account :)
I will check why I decided to ignore the placeholder and if it is possible I will add it.
I will keep you posted 📬

**Comment by iulian-radu-at** [comment]
The placeholder was initially ignored as it can be overlapped by the label.
Starting with version 1.2.1 you can use a placeholder as long as there is no label defined.
To set the placeholder:
```
<SingleSelect
    style={{width: "85%"}}
    placeholder="--- your placeholder here ---"
    value={field.input.value}
    options={field.options}
    onChange={field.input.onChange}
/>
```
As you can see, you set it directly in the props of SingleSelect and not in SelectProps.placeholder
Please check if it works as expected or it needs more improvements. Thanks.

**Comment by korshavn** [comment]
Thank you! It works. :-)

**Comment by iulian-radu-at** [comment]
I am happy that you are happy :smiley:
