### ISSUE TITLE
Styling for bottom line

### ISSUE THREAD

**Issue by sseekamp0** [iulian-radu-at/react-select-material-ui#24]
Hi!
I'm having trouble being able to style the bottom line/bottom border line when the field is in focus. It defaults to the material-ui purple, but I'm needing to change both the above label (in focus label) color and the bottom line. Do you have any examples of how to do that? Any examples of doing it via using the singleselect component?

I've tried using InputLabelProps but can't seem to find a property to style the bottom border. I was able to use the color property to style the label, but I'm wondering if I can style only the popup label and not the actual field label. Can't find a way to style them independently.

Thanks!

**Comment by iulian-radu-at** [comment]
You need to define a style function for **control**. The "trick" is to use the value of state.isFocused to decide which color to be used for the bottom border.
Bellow you find an example, which is also added in storybook to the **styled** example:

```
control: (base: any, state: any) => ({
      ...base,
      background: 'transparent',
      borderBottom: state.isFocused ? '#ff0000' : '#ffff80',
      borderBottomWidth: 3,
      borderBottomStyle: 'solid',
      borderLeftWidth: 0,
      borderRightWidth: 0,
      borderTopWidth: 0,
      borderRadius: 0,
      boxShadow: 'none',
      marginRight: 25
    }),
```

**Comment by iulian-radu-at** [comment]
Closed as no answer from issuer in more then 14 days.
