### ISSUE TITLE
SingleSelect ignores the "color" attribute

### ISSUE THREAD

**Issue by Asatelit** [iulian-radu-at/react-select-material-ui#27]
SingleSelect ignores the "color" attribute and renders this select using the primary color palette.
![E__Dev_Projects_asatelit-helios-station_public_pre (1)](https://user-images.githubusercontent.com/5496004/69339653-7e1d3280-0c6e-11ea-9936-d9c106aaa049.png)

**Comment by iulian-radu-at** [comment]
Yes, as the material-ui theme is ignored (for the moment).
You can apply a custom style. See how it is done in storybook.
