### ISSUE TITLE
MultipleSelect  not working in IE11 or lower

### ISSUE THREAD

**Issue by souravsatyam** [iulian-radu-at/react-select-material-ui#29]
I am using MultipleSelect from library 'react-select-material-ui'. It seems to work fine in all modern browser such as chrome, mozilla, Safari but for Internet explorer version 11 it is throwing error.

SCRIPT5007: Unable to get property 'root' of undefined or null reference 0.chunk.js (230075,7)

Although the demo link for multiple select with creating new options seems to work fine in IE11

Here is below code "options" variable is have data and I have changeMenu method initialized.

```
<MultipleSelect
                        label="Choose or add menus"
                        values={options}
                        options={options}
                        onChange={this.changeMenu}
                        SelectProps={{
                          isCreatable: true,
                        }}
                      />
```

**Comment by iulian-radu-at** [comment]
Hi @souravsatyam,

I think that your problem can be the same with the one reported here:
https://github.com/mui-org/material-ui/issues/17789

Please check that material-ui issue and let me know if it helped you to solve it.

Cheers,
Iulian

**Comment by souravsatyam** [comment]
Yes, Issue is same.  Used **import 'core-js/es/object';** but resulted in same error. 
. Does **react-select-material-ui** have documentation mentioning the browser support?

**Comment by iulian-radu-at** [comment]
Hi @souravsatyam,

According to JedWatson 

> Supported browsers are now IE11+ and "last 2 versions" of everything else, as defined in the .browserslistrc file in v2.

He mentioned this on Feb 2nd, 2019: https://github.com/JedWatson/react-select/issues/15

The supported browsers for react-select-material-ui are the same as react-select.

I hope that this answer your question about browser support.

Cheers,
Iulian

**Comment by souravsatyam** [comment]
Hi @iulian-radu-at ,

I believe last time issue was reproducible in IE11 Although yes react-select-material-ui uses react-select module. But I cannot find the browser support documentation for this(react-select-material-ui) specific library.
Thanks for doing research for me

Thanks

**Comment by iulian-radu-at** [comment]
Hi @souravsatyam,

There is none.
As material-select does not provide one, I cannot produce one for react-select-material-ui.

Sorry,
Iulian
