### ISSUE TITLE
How can i make the select variant="outlined"?

### ISSUE THREAD

**Issue by avaldevilap** [iulian-radu-at/react-select-material-ui#3]

**Comment by iulian-radu-at** [comment]
Hi Alejandro,
This is something I need to implement.

**Comment by avaldevilap** [comment]
ok i will clone the repo

**Comment by avaldevilap** [comment]
I had to make my own component

**Comment by iulian-radu-at** [comment]
@avaldevilap when you made your own component based on my component, then maybe you can contribute it via a PR.

**Comment by ningappa** [comment]
Any update on this?

**Comment by iulian-radu-at** [comment]
Maybe you can use custom styling for obtaining it.

**Comment by MHM5000** [comment]
Any updates?
