### ISSUE TITLE
If the values prop is passed to a single select, "isClearable" is always false.

### ISSUE THREAD

**Issue by joshleblanc** [iulian-radu-at/react-select-material-ui#32]
Reproduction: https://codesandbox.io/s/silly-snyder-equue?file=/src/ClearValues.tsx

**Comment by iulian-radu-at** [comment]
Hi @joshleblanc,

Thanks for reporting this problem.

The fix should be already in 6.5.0. Also I added a storybook for this issue.
Please check it and let me know if it works as expected.

Cheers,
Iulian

**Comment by joshleblanc** [comment]
Works great!
