### ISSUE TITLE
Default import no longer works

### ISSUE THREAD

**Issue by joshleblanc** [iulian-radu-at/react-select-material-ui#35]
Reproduction: https://codesandbox.io/s/xenodochial-https-i700w?file=/src/App.js

I don't know why this is happening, but it might be related to the upgrade to typescript 3.9?

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#breaking-changes

Maybe this?

```
export * is Always Retained #
In previous TypeScript versions, declarations like export * from "foo" would be dropped in our JavaScript output if foo didn’t export any values. This sort of emit is problematic because it’s type-directed and can’t be emulated by Babel. TypeScript 3.9 will always emit these export * declarations. In practice, we don’t expect this to break much existing code.
```

**Comment by iulian-radu-at** [comment]
Hi @joshleblanc,

Thanks for reporting this problem. Version 6.6.2 should work correct now. Please check if it works for you too and let me know.

Thanks,
Iulian

**Comment by joshleblanc** [comment]
Works!
