### ISSUE TITLE
Can't set object values in MultipleSelect

### ISSUE THREAD

**Issue by mohitgarg** [iulian-radu-at/react-select-material-ui#39]
MultipleSelect only pre-fills only if the `values` is an array of strings. If I am passing an array of objects like you do with `selectOptions` on `onChange`, input field doesn't get populated.

Here's the sandbox link:
https://codesandbox.io/s/friendly-minsky-xw6il

**Comment by iulian-radu-at** [comment]
Hi @mohitgarg,

This is by design.
You can take your SelectOptions and extract the values in an array which is provided to MultipleSelect's values prop.

Cheers,
Iulian
