### ISSUE TITLE
Help - Wondering how to fix a possible zIndex overlay

### ISSUE THREAD

**Issue by josoroma** [iulian-radu-at/react-select-material-ui#41]
Hi!

I am having bit problem trying to add/override styles, for example, to change zIndez position of select options menu:

![image](https://user-images.githubusercontent.com/69951/111882088-34834b80-8979-11eb-810f-c1d4cd7fe77e.png)

![image](https://user-images.githubusercontent.com/69951/111882093-3d741d00-8979-11eb-9d27-285ebd3dd5f8.png)

Thank you!

**Comment by iulian-radu-at** [comment]
Hi @josoroma ,

I think that you can fix this problem using css with z-index for your components. You should not need to do any "magic" to react-select-material-ui.

If you can provide a code which reproduces this problem, I can take a look :D

Cheers,
Iulian

**Comment by josoroma** [comment]
Thank you @iulian-radu-at ! it works with a className!

**Comment by iulian-radu-at** [comment]
Glad to read that @josoroma.
