### ISSUE TITLE
Error - It looks like there are several instances of `@material-ui/styles` initialized in this application

### ISSUE THREAD

**Issue by josoroma** [iulian-radu-at/react-select-material-ui#42]
Hi!

I am hitting this error:

```
It looks like there are several instances of `@material-ui/styles` initialized in this application. This may cause theme propagation issues, broken class names, specificity issues, and makes your application bigger without a good reason.
```

![image](https://user-images.githubusercontent.com/69951/112419967-f88e1480-8cf1-11eb-8460-e0baa7327cb4.png)

![image](https://user-images.githubusercontent.com/69951/112419986-02177c80-8cf2-11eb-86a1-3640ab6672dc.png)

Reference: https://material-ui.com/getting-started/faq/#i-have-several-instances-of-styles-on-the-page

**Comment by iulian-radu-at** [comment]
Hi @josoroma,

It looks like you need to upgrade your version of @material-ui/core to 4.11.3
It looks like you have it now at 4.11.2

Cheers,
Iulian

**Comment by josoroma** [comment]
Thanks a bunch!
