### ISSUE TITLE
MUI v5 migration

### ISSUE THREAD

**Issue by denneulin** [iulian-radu-at/react-select-material-ui#44]
Hi,

Thanks for your great library.
Do you plan to migrate to mui v5 ?

It requires to replace your dependency `@material-ui/core` by `@mui/material`

Actually it is not possible to migrate to mui v5 when using your lib because of this https://github.com/mui-org/material-ui/pull/28907/files

**Comment by denneulin** [comment]
I guess I am missing something then. 

I don't see the 8..0.0 tag here https://www.npmjs.com/package/react-select-material-ui-tags

**Comment by iulian-radu-at** [comment]
I still need to update all other packages depending on it. I did not knew that you are using the other one. I will inform you once the other one is updated.
