### ISSUE TITLE
How to reduce bundled size of react-select-material-ui?

### ISSUE THREAD

**Issue by hnhegde** [iulian-radu-at/react-select-material-ui#46]
I am using react-select-material-ui for a form in my [blog](https://blog.squaredeal.tax/how-to-lower-property-taxes-in-Texas/). The component is pretty useful. Thanks to @iulian-radu-at for developing it. 
Howeve this component seems to have a large footprint. As per bundle analyzer, `react-select-material-ui` seems to contribute significantly to the bundle size. Any idea how to reduce the size?

PFA bundle analysis screenshot. Lodash seems to be the major contributor. 

![image](https://user-images.githubusercontent.com/4962589/197126624-6fe43ac2-9f87-4e7d-ad65-0a981b9a8bfc.png)

![image](https://user-images.githubusercontent.com/4962589/197126488-85c60eb7-db4c-4a89-9887-535c6912f68d.png)

**Comment by iulian-radu-at** [comment]
Hi @hnhegde,

I just published the v9 and I hope it will "fix" your problem.

Please check it and let me know.

Cheers,
Iulian

**Comment by hnhegde** [comment]
Much better! Thank you @iulian-radu-at 
![image](https://user-images.githubusercontent.com/4962589/197714111-57a67b15-4e13-46d0-ad72-6a39dff71113.png)
