### ISSUE TITLE
Suggestion: Interaction with the <Dialog /> component of the material-ui

### ISSUE THREAD

**Issue by LeonardoSidney** [iulian-radu-at/react-select-material-ui#5]
Hi, I bring this issue more as a suggestion, after all I'm not sure what the project proposal is, but I believe my point of view is valid:
![Captura de Tela_selecionar área_20190321152511](https://user-images.githubusercontent.com/4030991/54776864-e069f300-4c08-11e9-8497-06e231c6473f.png)
![Captura de Tela_selecionar área_20190321152558](https://user-images.githubusercontent.com/4030991/54776861-e069f300-4c08-11e9-98d3-0808f911614c.png)

Currently the interaction with the <Dialog /> component could be improved from my point of view of course, making the "dialog box" component overlap the <Dialog /> component instead of "increasing its size" by generating this sidebar in a "modal selection"

Thanks for listening

**Comment by ColinKrist** [comment]
I too just faced this issue. 
apply this fix: https://github.com/mui-org/material-ui/issues/7431 in this comment: https://github.com/mui-org/material-ui/issues/7431#issuecomment-414703875
and you'll be good.

**Comment by LeonardoSidney** [comment]
Ty, thats works to me.
